### ISSUE TITLE
이미지 파일 (public) 관리 논의

### ISSUE THREAD

**Issue by CheolWoongChoi** [Side-Project-Since-04/wepl-fe#48]
이미지를 어떻게 관리할 지 논의하면 좋을 것 같은데요.
두 가지 얘기하면 좋을 것 같습니다.

1. 이미지 네이밍
2. 이미지 파일 위치

1번 논의)
일단, 이미지 파일 네이밍은 스네이크 케이스와 케밥 케이스를 많이 쓰이는 것 같은데요.
정민님이 업로드한 파일 네이밍 보니까 케밥 케이스 (icon-arrow-right.svg) 로 쓰이는 것 같더라고요.
그래서, 케밥 케이스를 쓰고, 네이밍이 이상하지 않는 이상 정민님이 작성하신 파일 네이밍대로 쓰면 좋을 것 같아요.

2번 논의)
client 앱에서 쓰이는 이미지는 apps/client/public에 페이지 경로에 맞게 폴더를 만들어서 관리해주면 될 것 같고,
packages/ui/컴포넌트에 쓰이는 이미지는 컴포넌트 폴더 하위에 public 같은 폴더를 둬서 관리해주면 좋을 것 같아요.

관리하기 애매하거나, 분류가 애매한 경우에는 사용처 가까운 곳에 이미지 파일을 두면 될 것 같고요.

1번, 2번 예시)
<img width="418" alt="스크린샷 2024-06-07 오후 10 40 40" src="https://github.com/Side-Project-Since-04/wepl-fe/assets/24875185/a14fbc5e-e98f-48c2-a003-d6caae200e47">
<img width="418" alt="스크린샷 2024-06-07 오후 10 41 01" src="https://github.com/Side-Project-Since-04/wepl-fe/assets/24875185/ffc9eed2-04fa-4d6e-bf90-e01deece21b1">

**Comment by jun0811** [comment]
넵 좋습니다!
